const taskData=[
    {"id": 1, "taskName": "Wake at 6 A.M"},
    {"id": 2, "taskName": "Exercise for 30 minutes"},
    {"id": 3, "taskName": "Prepare breakfast"},
    {"id": 4, "taskName": "Read the news"},
    {"id": 5, "taskName": "Check emails"},
    {"id": 6, "taskName": "Attend morning meeting"},
    {"id": 7, "taskName": "Work on project A"},
    {"id": 8, "taskName": "Have lunch"},
    {"id": 9, "taskName": "Review project B"},
    {"id": 10, "taskName": "Submit report"},
    {"id": 11, "taskName": "Attend afternoon meeting"},
    {"id": 12, "taskName": "Reply to emails"},
    {"id": 13, "taskName": "Prepare for tomorrow's presentation"},
    {"id": 14, "taskName": "Go for a walk"},
    {"id": 15, "taskName": "Prepare dinner"},
    {"id": 16, "taskName": "Watch a movie"},
    {"id": 17, "taskName": "Read a book"},
    {"id": 18, "taskName": "Plan next day's tasks"},
    {"id": 19, "taskName": "Call family"},
    {"id": 20, "taskName": "Clean the house"},
    {"id": 21, "taskName": "Do laundry"},
    {"id": 22, "taskName": "Water the plants"},
    {"id": 23, "taskName": "Practice a hobby"},
    {"id": 24, "taskName": "Go to bed by 10 P.M"},
    {"id": 25, "taskName": "Meditate for 10 minutes"}
]
module.exports=taskData